import Head from 'next/head';
import Header from '../components/layout/header/Header'
import HeroBanner from '../components/layout/herobanner/HeroBanner'
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <HeroBanner></HeroBanner>
      </main>
    </>
  );
}
